[package]
name = "NivraCourt"
edition = "2024.beta"
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
authors = ["Rasmus Suni (rasmus.suni@nivracourt.io)", "Elmeri Kemppainen (elmeri.kemppainen@gmail.com)"]

[dependencies]


[addresses]
nivra_court = "0x0"

[dev-dependencies]


[dev-addresses]