[package]
name = "nivra"
edition = "2024"

[dependencies]
seal = { git = "https://github.com/MystenLabs/seal.git", subdir = "move/seal", rev = "seal-v0.6.2" }
nvr = { git = "https://github.com/NivraLabs/nivra-court.git", subdir = "packages/nvr", rev = "main" }